services:
  - type: worker
    name: voltage-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TOKEN
        sync: false